{"count":8,"days":[{"date":"2021-01-12T00:00:00.000Z","count":0,"incidents":[],"order":1},{"date":"2021-01-11T00:00:00.000Z","count":0,"incidents":[],"order":2},{"date":"2021-01-10T00:00:00.000Z","count":0,"incidents":[],"order":3},{"date":"2021-01-09T00:00:00.000Z","count":0,"incidents":[],"order":4},{"date":"2021-01-08T00:00:00.000Z","count":0,"incidents":[],"order":5},{"date":"2021-01-07T00:00:00.000Z","count":0,"incidents":[],"order":6},{"date":"2021-01-06T00:00:00.000Z","count":0,"incidents":[],"order":7},{"date":"2021-01-05T00:00:00.000Z","count":1,"incidents":[{"id":"570cd1dd","title":"Temporary Cluster outage","date":"2021-01-05T01:36:38.720Z","modified":"2021-01-05T01:39:52.388Z","scheduled":null,"severity":"major-outage","affectedsystems":["cluster"],"resolved":true,"content":"<p>Launching jobs using Slurm or using Jupyterhub may fail.</p>\n<!--- language code: en -->\n"}],"order":8}],"daysSinceLatest":7}